### PR TITLE
Controls to add/remove rows/columns

### PR DESCRIPTION
**Pull request by agereaude**
In relation to this ticket: https://github.com/yabwe/medium-editor-tables/issues/8

I've added 6 buttons below the grid to add and remove rows and columns. These buttons only appear if the cursor is inside a td.

There are no font-awesome icons that express exactly these operations. They probably need to be changed. The styles also might need to be adjusted.

### CODE REVIEW

**Comment by daviferreira** [comment]
Nice stuff.

Before I merge we need some better stylin' I guess. I would completely hide the grid itself, and only show the controls, while inside a table. What do you think?

Another small issue, when you add a row, the cells are empty, so you can't really focus on then. We need to add a `<br />`.

I can jump in and help you if you want, let me know! And thanks a lot for the contribution :)

**Comment by agereaude** [comment]
Thanks, I've just added that <br>

I thought about hiding the grid, but maybe there's a use case for inserting a table inside another table. Hiding the grid would prevent that. Maybe the controls should be placed above the grid.

I wouldn't know how to style things better, so any help is more than welcome.

**Comment by agereaude** [comment]
I've added some labels and styles and moved the buttons above the grid.
Still not sure that those are the best font-awesome icons to represent these actions.

**Comment by agereaude** [comment]
I've also added a button to remove the table (https://github.com/yabwe/medium-editor-tables/issues/3)

**Comment by daviferreira** [comment]
Sorry for the delay, @gerherz, I will merge it soon. Just need some time to proper review it :)

**Comment by agereaude** [comment]
No problem, take your time.

**Comment by krisdahl** [comment]
This would be really nice to get merged.  Nice work guys.

**Comment by digitallawyer** [comment]
+1. Thanks for all the work on this, much appreciated!

**Comment by boynet** [comment]
possible to update the demo http://yabwe.github.io/medium-editor-tables/ ?

**Comment by makeittech** [comment]
Thanks for your work. I've got an issue: when removing a row, visually it removes, but changes are not submitting, so after saving I still see my table with all rows and it's content. Is there some way to fix it?

**Pull request merged**
