### PR TITLE
restrict table inside table

### PR DESCRIPTION
**Pull request by durgeshahire4**
issues #37  

@j0k3r Can you please review this PR. Thanks

### CODE REVIEW

**Comment by durgeshahire4** [comment]
```
var editor = new MediumEditor(editableBlock, {
  extensions: {
    table: new MediumEditorTable({
      restrictNestedTable: true
    })
  }
});
```

Default value of restrictNestedTable should be false.

**Comment by j0k3r** [comment]
Could you add some tests about it?

**Comment by durgeshahire4** [comment]
@j0k3r  Thanks for immediate response.
I don't think so unit test cases required for this small change

**Comment by j0k3r** [comment]
Even if it's small it's still better with unit test

**Comment by durgeshahire4** [comment]
@j0k3r Is there any help guide for tests? because there is no tests for `builder.js`

**Comment by durgeshahire4** [comment]
@j0k3r any inputs??

**Comment by j0k3r** [comment]
No sorry.
But I'll merge it anyway.

**Comment by durgeshahire4** [comment]
@j0k3r Thanks

**Comment by durgeshahire4** [comment]
@j0k3r Can you please release new version so that we can used newer version in our project.
Thanks in advanced!

**Pull request merged**
